### ISSUE TITLE
`Result::unwrap()` on an `Err

### ISSUE THREAD

**Issue by eneroth** [automerge/automerge-java#4]
Calling `splice` on a non-text field crashes the JVM with the following message:

```
thread '<unnamed>' panicked at src/read_methods.rs:301:58:
called `Result::unwrap()` on an `Err` value: GetRaw(NullPtr("get_object_class"))
```

**Comment by alexjg** [comment]
Yeah this is bad, I'll try and get a fix in today with the update to the Java library I'm working on

**Comment by eneroth** [comment]
Is there a way in userland to check the presence/absence and type of an entry given an `ObjectId`?

**Comment by alexjg** [comment]
There is not, tracking that in #5

**Comment by alexjg** [comment]
I believe the "non text field" part of this is a red herring. I think the actual problem is passing `null` as the object ID, adding a few more dollars to that old mistake I guess. We should obviously not crash the JVM here though, I'll add a bunch of null checks.

**Comment by eneroth** [comment]
Ah, so let me get this right so I can understand the error I made: 
1. I got an ObjectId pointing into the void
2. I run _anything_ on that (not just `text`) -> problem

**Comment by alexjg** [comment]
It's not so much an `ObjectId` pointing into the void as an `ObjectId` which is somehow `null`. Now, one question is how that happened, I don't think we return `null` `ObjectId`s anywhere.

**Comment by eneroth** [comment]
Ah… No, I see what the problem is then. Definitely my fault. I think I interjected a null there, I don't think Automerge returned one.
